###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "firstname": "Senthil",
    "lastname": "G",
    "age": 34
}
###
GET http://localhost:5000/users/5f6d4df76d36ee596e6fad2f

###
DELETE  http://localhost:5000/users/5f6d588852e923678b9f3437

###
PATCH  http://localhost:5000/users/5f782bfb4852457570a6c8e0
Content-Type: application/json

{
    "lastname": "Gunasekaran"
}